[[hooks]]
id = "2810076c-1f3a-4cf6-8aa8-70d6d5611326"
name = "Set default repository when the repository forked"
repo-pattern = ""
trigger-event = "post-fork"
operation-type = "script"
operation-id = "c4b4d546-f16f-44a7-b3cd-00efa6df333b"

[[hooks]]
id = "6f0f4029-e9d6-445c-81a5-99b9d821ccae"
name = "Set default repository when the forked-repository cloned"
repo-pattern = ""
trigger-event = "post-clone"
operation-type = "script"
operation-id = "c4b4d546-f16f-44a7-b3cd-00efa6df333b"

[[hooks]]
id = "5d3ab0da-d38e-4a70-99bd-1babafb9c5d3"
name = "Trust Codex project when the repository created"
repo-pattern = ""
trigger-event = "post-create"
operation-type = "script"
operation-id = "c8d14ab2-fc99-41d8-bd98-4006487cfdb2"

[[hooks]]
id = "f611a561-1393-48a9-b733-4664b086eb64"
name = "Trust Codex project when the repository cloned"
repo-pattern = ""
trigger-event = "post-clone"
operation-type = "script"
operation-id = "c8d14ab2-fc99-41d8-bd98-4006487cfdb2"
