check_for_update_on_startup = false
update_on_startup = false
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[mcp_servers.nvim_proxy]
url = "http://127.0.0.1:37125/mcp"

[profiles.local-qwen]
model = "qwen3-vl:30b"
model_provider = "ollama"

[model_providers.ollama]
name = "Ollama"
base_url = "http://localhost:11434/v1"

[projects."/home/kyoh86/Projects/github.com/kyoh86/dotfiles"]
trust_level = "trusted"

[projects."/home/kyoh86"]
trust_level = "untrusted"

[projects."/home/kyoh86/Projects/github.com/kyoh86/denops-docbase.vim"]
trust_level = "trusted"

[projects."/home/kyoh86/Projects/github.com/kyoh86/google-ime-dict"]
trust_level = "trusted"

[projects."/home/kyoh86/Projects/github.com/kyoh86/qlean.nvim"]
trust_level = "trusted"

[projects."/home/kyoh86/Projects/github.com/jdx/mise"]
trust_level = "trusted"

[projects."/home/kyoh86/Projects/github.com/kyoh86/ddu-source-lazy_nvim"]
trust_level = "trusted"

[projects."/home/kyoh86/Projects/github.com/kyoh86/ddu-source-github"]
trust_level = "trusted"

[projects."/home/kyoh86/Projects/github.com/kyoh86/denops-mdlink.vim"]
trust_level = "trusted"
